# 推荐系统默认配置文件

# 数据库配置
database:
  mysql:
    host: localhost
    port: 3306
    user: root
    password:
    database: recommend_system
    charset: utf8mb4
    pool_size: 10
    pool_recycle: 3600
    pool_timeout: 30

# Redis配置 - 已禁用
redis:
  enabled: false
  # 以下配置仅作为参考，系统不会使用
  host: localhost
  port: 6379
  db: 0
  password: null
  socket_timeout: 5
  socket_connect_timeout: 5
  retry_on_timeout: true
  health_check_interval: 30

# 缓存配置
cache:
  memory:
    enabled: true
    max_size: 20000 # 增加内存缓存大小，因为没有Redis作为备份
    ttl: 3600 # 默认过期时间(秒)
    cleanup_interval: 300 # 清理间隔(秒)
  redis:
    enabled: false
    default_ttl: 3600 # 默认过期时间(秒)
  strategy:
    hot_topics_ttl: 300 # 热点话题缓存时间(秒)
    user_recommendations_ttl: 3600 # 用户推荐结果缓存时间(秒)
    system_config_ttl: 86400 # 系统配置缓存时间(秒)

# 推荐引擎配置
recommender:
  model_dir: ./models
  default_top_n: 50
  similarity_threshold: 0.7 # 默认相似度阈值
  diversity_weight: 0.2 # 默认多样性权重
  algorithms:
    tfidf:
      enabled: true
      weight: 0.6
    collaborative:
      enabled: true
      weight: 0.4
  infinite_scroll:
    enabled: true
    # 分层推荐策略
    tiers:
      tier1:
        max_page: 3 # 前3页
        similarity_threshold: 0.7 # 严格个性化推荐
        diversity_weight: 0.2
        pool_weights:
          hot: 0.2
          new: 0.1
          quality: 0.7
      tier2:
        max_page: 10 # 4-10页
        similarity_threshold: 0.56 # 降低20%相似度阈值
        diversity_weight: 0.3 # 增加50%多样性
        pool_weights:
          hot: 0.4
          new: 0.3
          quality: 0.3
      tier3:
        # 10页以后
        similarity_threshold: 0.42 # 降低40%相似度阈值
        diversity_weight: 0.4 # 增加100%多样性
        pool_weights:
          hot: 0.3
          new: 0.5
          quality: 0.2
    # 已浏览内容记录
    viewed_items:
      ttl: 604800 # 7天过期时间(秒)
      max_size: 10000 # 每用户最大记录数

# 曝光池配置
exposure_pool:
  new_posts:
    capacity: 1000
    weight: 0.5
    max_age_hours: 24
  hot_posts:
    capacity: 500
    weight: 0.3
    min_heat_score: 10.0
  quality_posts:
    capacity: 300
    weight: 0.2
    min_quality_score: 0.7
    max_age_days: 30
  diversity_posts:
    capacity: 200
    weight: 0.1
    min_category_count: 5
  refresh_interval: 600 # 刷新间隔(秒)

# 热点话题配置
hot_topics:
  top_n: 50
  time_window_hours: 24
  min_interactions: 5
  weights:
    view: 1.0
    like: 3.0
    collect: 4.0
    comment: 5.0
    share: 4.0
  time_decay_factor: 0.8
  update_interval: 300 # 更新间隔(秒)

# 任务调度配置
scheduler:
  num_workers: 4
  log_file: ./logs/tasks.log
  max_history: 1000
  tasks:
    model_update:
      schedule: daily
      time: "00:30"
      priority: 10
      max_retries: 3
    hot_topics:
      schedule: interval
      interval: 300
      priority: 8
      max_retries: 2
    batch_recommendations:
      schedule: interval
      interval: 3600
      priority: 5
      max_retries: 3
    exposure_refresh:
      schedule: interval
      interval: 600
      priority: 7
      max_retries: 2
    data_cleanup:
      schedule: daily
      time: "02:00"
      priority: 3
      max_retries: 3

# 日志配置
logging:
  level: INFO
  console: true
  file:
    enabled: true
    path: ./logs/recommend_system.log
    max_size_mb: 100
    backup_count: 10
  format: "%(asctime)s [%(name)s] %(levelname)s: %(message)s"
  date_format: "%Y-%m-%d %H:%M:%S"

# 系统限流配置
rate_limit:
  enabled: true
  default_limit: 100 # 每分钟请求数
  window_size: 60 # 窗口大小(秒)
  by_user: true # 是否按用户限流

# 熔断配置
circuit_breaker:
  enabled: true
  failure_threshold: 5 # 失败阈值
  recovery_timeout: 30 # 恢复超时(秒)
  services:
    database:
      enabled: true
      failure_threshold: 3
      recovery_timeout: 60
    redis:
      enabled: false # 禁用Redis熔断
      failure_threshold: 3
      recovery_timeout: 30

# 监控配置
monitoring:
  enabled: true
  metrics_port: 8000
  collect_interval: 15 # 收集间隔(秒)
  endpoints:
    prometheus: true
    health: true
    info: true

# API配置
api:
  host: 0.0.0.0
  port: 5000
  debug: false
  version: 1.0.0
  rate_limit:
    enabled: true
    default_limit: 100 # 每分钟请求数
    recommendations_limit: 60 # 推荐接口每分钟请求数
  pagination:
    default_page_size: 20
    max_page_size: 100
    infinite_scroll: true # 启用无限滚动
